"""The control surface must never claim a capability the model lacks.

A knob that silently does nothing is worse than a missing knob: it corrupts the
evaluation, because a song generated by a model that ignored BPM would be scored
as though BPM had been requested and honoured.
"""

import pytest

from songforge.generation import (
    CONTROLS,
    Capabilities,
    ControlSupport,
    Section,
    SongRequest,
    VocalSpec,
    load_prompts,
    parse_lyric_sections,
    resolve_controls,
)

BENCHMARK = "benchmarks/prompts.yaml"


def caps(**overrides) -> Capabilities:
    controls = dict.fromkeys(CONTROLS, ControlSupport.NATIVE)
    controls.update(overrides.pop("controls", {}))
    defaults = {
        "model": "test", "version": "1", "controls": controls,
        "max_duration_seconds": 120.0, "sample_rate": 44100, "produces_vocals": True,
    }
    defaults.update(overrides)
    return Capabilities(**defaults)


# --- capabilities must be complete ---------------------------------------


def test_capabilities_reject_an_undeclared_control():
    """Silence about a control is how fake knobs get created."""
    partial = dict.fromkeys(CONTROLS, ControlSupport.NATIVE)
    partial.pop("bpm")
    with pytest.raises(ValueError, match="bpm"):
        Capabilities(model="m", version="1", controls=partial, max_duration_seconds=60, sample_rate=44100)


def test_capabilities_reject_an_unknown_control():
    controls = dict.fromkeys(CONTROLS, ControlSupport.NATIVE)
    controls["telepathy"] = ControlSupport.NATIVE
    with pytest.raises(ValueError, match="telepathy"):
        Capabilities(model="m", version="1", controls=controls, max_duration_seconds=60, sample_rate=44100)


# --- unsupported controls must surface ------------------------------------


def test_ignored_control_that_was_requested_warns():
    request = SongRequest(prompt="a song", bpm=120)
    resolution = resolve_controls(request, caps(controls={"bpm": ControlSupport.IGNORED}))
    assert not resolution.honest
    assert any("bpm" in w for w in resolution.warnings)


def test_ignored_control_that_was_not_requested_is_silent():
    """A model that ignores key is irrelevant to a request with no key."""
    request = SongRequest(prompt="a song")
    resolution = resolve_controls(request, caps(controls={"key": ControlSupport.IGNORED}))
    assert resolution.honest


def test_prompt_level_support_is_labelled_as_soft():
    request = SongRequest(prompt="a song", bpm=120)
    resolution = resolve_controls(request, caps(controls={"bpm": ControlSupport.PROMPT}))
    assert resolution.honest, "a soft control is honoured, just not guaranteed"
    assert "soft" in resolution.applied["bpm"]


def test_requesting_vocals_from_an_instrumental_model_warns():
    request = SongRequest(prompt="a song", lyrics="[Verse]\nhello")
    resolution = resolve_controls(request, caps(produces_vocals=False))
    assert any("vocals" in w for w in resolution.warnings)


def test_duration_beyond_the_model_limit_warns():
    request = SongRequest(prompt="a song", duration_seconds=300)
    resolution = resolve_controls(request, caps(max_duration_seconds=120))
    assert any("duration" in w for w in resolution.warnings)


def test_unsupported_vocal_language_warns():
    request = SongRequest(prompt="a song", vocal=VocalSpec(language="bn"))
    resolution = resolve_controls(request, caps(languages=("en", "zh")))
    assert any("bn" in w for w in resolution.warnings)


def test_a_fully_supported_request_is_honest():
    request = SongRequest(prompt="a song", bpm=100, key="C major", lyrics="[Verse]\nhi",
                          vocal=VocalSpec(language="en"))
    resolution = resolve_controls(request, caps(languages=("en",)))
    assert resolution.honest
    assert resolution.warnings == []


# --- request semantics -----------------------------------------------------


def test_request_reports_only_the_controls_it_set():
    request = SongRequest(prompt="a", bpm=90)
    requested = request.requested_controls()
    assert {"prompt", "seed", "duration", "bpm"} <= requested
    assert "key" not in requested and "lyrics" not in requested


def test_empty_prompt_is_rejected():
    with pytest.raises(ValueError, match="prompt"):
        SongRequest(prompt="   ").validate()


def test_implausible_bpm_is_rejected():
    with pytest.raises(ValueError, match="bpm"):
        SongRequest(prompt="a", bpm=5).validate()


def test_unknown_section_kind_is_rejected():
    with pytest.raises(ValueError, match="chorusish"):
        SongRequest(prompt="a", structure=(Section(kind="chorusish"),)).validate()


def test_fingerprint_is_stable_and_distinguishes_seeds():
    a = SongRequest(prompt="a song", seed=1)
    b = SongRequest(prompt="a song", seed=2)
    assert a.fingerprint() == SongRequest(prompt="a song", seed=1).fingerprint()
    assert a.fingerprint() != b.fingerprint()


def test_round_trip_through_dict():
    request = SongRequest(prompt="a", lyrics="[Verse]\nx", genre=("pop",), bpm=100,
                          vocal=VocalSpec(gender="female"), structure=(Section("intro", 8.0),))
    assert SongRequest.from_dict(request.to_dict()) == request


# --- lyric structure -------------------------------------------------------


def test_lyric_tags_become_sections():
    sections = parse_lyric_sections("[Verse]\nline one\n\n[Chorus]\nline two")
    assert [s.kind for s in sections] == ["verse", "chorus"]
    assert sections[0].lyrics == "line one"


def test_unknown_lyric_tag_is_kept_as_text_not_guessed():
    """Better to carry an unmodelled tag through than to map it to the wrong section."""
    sections = parse_lyric_sections("[Verse]\nline\n[Refrain]\nother")
    assert [s.kind for s in sections] == ["verse"]
    assert "[Refrain]" in sections[0].lyrics


# --- the benchmark set itself ----------------------------------------------


def test_benchmark_prompt_set_loads_with_the_agreed_ids():
    requests = load_prompts(BENCHMARK)
    ids = [r.extra["id"] for r in requests]
    assert ids == ["piano", "violin", "guitar", "rock", "edm", "cinematic", "vocal", "rich_mix"]


def test_every_benchmark_prompt_is_valid_and_seeded_identically():
    requests = load_prompts(BENCHMARK)
    seeds = {r.seed for r in requests}
    assert len(seeds) == 1, "candidates must be compared on one shared seed"
    for request in requests:
        request.validate()
        assert request.extra["expects_instruments"], f"{request.extra['id']} needs evaluation targets"


def test_vocal_prompts_carry_lyrics():
    requests = {r.extra["id"]: r for r in load_prompts(BENCHMARK)}
    assert requests["vocal"].lyrics and requests["rich_mix"].lyrics
    assert requests["vocal"].wants_vocals
    assert not requests["piano"].wants_vocals


# --- ACE-Step capability declaration ---------------------------------------


def test_acestep_declares_untyped_controls_as_soft_not_native():
    """genre/mood/instruments are caption text in ACE-Step, not typed fields.

    Declaring them NATIVE would tell the evaluation a style request was honoured
    as a constraint when the model only ever saw free text.
    """
    from songforge.generation.adapters.acestep import AceStepAdapter

    caps = AceStepAdapter().capabilities
    for control in ("genre", "mood", "instruments", "vocal_style", "structure"):
        assert caps.support(control) is ControlSupport.PROMPT, control
    for control in ("prompt", "lyrics", "duration", "bpm", "key", "seed"):
        assert caps.support(control) is ControlSupport.NATIVE, control


def test_acestep_records_code_and_weights_licences_separately():
    from songforge.generation.adapters.acestep import AceStepAdapter

    position = AceStepAdapter().license
    assert position.code_license == "MIT"
    assert position.weights_license == "MIT"
    assert position.sources, "a licence claim needs a source"


def test_acestep_prompt_composition_folds_in_the_untyped_controls():
    from songforge.generation.adapters.acestep import AceStepAdapter

    request = SongRequest(
        prompt="A cinematic song.", genre=("pop rock",), mood=("epic",),
        instruments=("piano", "strings"), vocal=VocalSpec(gender="female", style="powerful"),
    )
    text = AceStepAdapter()._compose_prompt(request)
    assert "pop rock" in text and "epic" in text
    assert "piano" in text and "strings" in text
    assert "female" in text and "vocal" in text


def test_acestep_marks_an_instrumental_request_explicitly():
    from songforge.generation.adapters.acestep import AceStepAdapter

    request = SongRequest(prompt="A piano piece.", vocal=VocalSpec(present=False))
    assert "instrumental" in AceStepAdapter()._compose_prompt(request)


def test_acestep_structure_only_request_still_emits_tags():
    from songforge.generation.adapters.acestep import AceStepAdapter

    request = SongRequest(prompt="edm", structure=(Section("intro"), Section("drop")))
    lyrics = AceStepAdapter()._compose_lyrics(request)
    assert "[intro]" in lyrics and "[drop]" in lyrics


def test_acestep_benchmark_requests_resolve_without_dropping_anything():
    """Every benchmark prompt must be expressible on this model."""
    from songforge.generation.adapters.acestep import AceStepAdapter

    caps = AceStepAdapter().capabilities
    for request in load_prompts(BENCHMARK):
        resolution = resolve_controls(request, caps)
        assert resolution.honest, (request.extra["id"], resolution.warnings)
