"""Turn generated songs into video scenes that play the actual audio.

WHY THIS IS SEPARATE FROM THE SLIDES
------------------------------------
A demo video for a music generator has to let the judge hear the music. Slides
describing the music are not a demo, and a scene that shows a waveform while
playing something else is worse than showing nothing.

So this script takes real (prompt, wav) pairs and nothing else. There is no
placeholder mode and no stock-music fallback: if no song was generated, no
demo scene is produced, and the video ships without one. The waveform on
screen is rendered by ffmpeg from the very audio stream that is muxed into the
clip, so the picture cannot disagree with the sound.

    python presentation/build_demo_scenes.py \\
        --demos demos.json \\
        --output-dir clips/

demos.json is a list of objects:

    [{"prompt": "Emotional Bengali cinematic alternative rock, ...",
      "wav": "outputs/song_01.wav",
      "seed": 8412, "duration": 30}]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from render_presentation_slides import (  # noqa: E402
    ACCENT, BG, CARD, LINE, MUTED, TEXT, W, H, bold, regular, wrap,
)
from PIL import Image, ImageDraw  # noqa: E402


def probe_duration(path: Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", str(path)],
        capture_output=True, text=True, check=True).stdout.strip()
    return float(out)


def render_backdrop(demo: dict, index: int, total: int, out: Path) -> Path:
    """The still frame the waveform is drawn over: the prompt, verbatim."""
    img = Image.new("RGB", (W, H), BG)
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, W, 8], fill=ACCENT)

    d.text((160, 110), f"Prompt {index} of {total}", font=bold(34),
           fill=ACCENT, anchor="lm")
    d.text((W - 160, 110), "generated by SongForge", font=regular(30),
           fill=MUTED, anchor="rm")

    # The prompt is shown exactly as it was submitted. A paraphrased or
    # tidied-up prompt would misrepresent what the model was actually asked.
    d.rounded_rectangle([160, 170, W - 160, 470], radius=20, fill=CARD)
    lines = wrap(d, f'"{demo["prompt"]}"', regular(40), W - 440)
    y = 230 if len(lines) > 3 else 270
    for line in lines[:5]:
        d.text((210, y), line, font=regular(40), fill=TEXT, anchor="lm")
        y += 58

    d.line([160, 560, W - 160, 560], fill=LINE, width=2)

    meta = []
    if demo.get("duration"):
        meta.append(f"{demo['duration']:g}s")
    if demo.get("seed") is not None:
        meta.append(f"seed {demo['seed']}")
    if demo.get("note"):
        meta.append(demo["note"])
    if meta:
        d.text((160, 930), "   ·   ".join(meta), font=regular(30),
               fill=MUTED, anchor="lm")

    d.rounded_rectangle([84, H - 96, 128, H - 52], radius=12, fill=ACCENT)
    d.text((138, H - 74), "SongForge", font=bold(26), fill=TEXT, anchor="lm")

    img.save(out)
    return out


def build_scene(demo: dict, index: int, total: int, out_dir: Path) -> Path:
    wav = Path(demo["wav"])
    if not wav.exists():
        raise SystemExit(f"missing audio: {wav}")

    backdrop = render_backdrop(demo, index, total, out_dir / f"demo_{index:02d}_bg.png")
    clip = out_dir / f"demo_{index:02d}.mp4"
    seconds = probe_duration(wav)

    # showwaves reads the same stream that gets muxed in, so the waveform is
    # the audio -- it cannot be footage of a different take.
    subprocess.run([
        "ffmpeg", "-y", "-loglevel", "error",
        "-loop", "1", "-framerate", "30", "-i", str(backdrop),
        "-i", str(wav),
        "-filter_complex",
        # showwaves is fed a gained copy purely so the trace is legible; the
        # stream muxed into the clip is the untouched original (-map 1:a), so
        # the gain changes the picture and never the sound.
        #
        # The trace is drawn white and then used as an ALPHA MASK over a flat
        # brand-colour plane, rather than asking showwaves for a coloured
        # trace. Two reasons: ffmpeg parsed 0xf87060 in showwaves' `colors`
        # into a teal-green, and keying the black background out by colour
        # threshold also erased the dim anti-aliased pixels that make the line
        # readable. alphamerge keeps every partial pixel at its true opacity.
        # The raw trace is thin and heavily anti-aliased, so most of its
        # pixels sit near black and would merge into a barely-visible line.
        # Lifting the mask multiplies opacity, not brightness, so the trace
        # reads solid without the line thickening into a smear.
        "[1:a]volume=4.0,showwaves=s=1600x320:mode=cline:colors=white:"
        "rate=30,format=gray,lutyuv=y='min(255,val*5)'[mask];"
        "color=c=0xf87060:s=1600x320:r=30[plane];"
        "[plane][mask]alphamerge[wave];"
        "[0:v][wave]overlay=(W-w)/2:620:shortest=1[v]",
        "-map", "[v]", "-map", "1:a",
        "-c:v", "libx264", "-preset", "medium", "-crf", "18",
        "-pix_fmt", "yuv420p", "-r", "30",
        "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-ac", "2",
        "-t", f"{seconds:.3f}", str(clip),
    ], check=True)
    return clip


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--demos", required=True,
                    help="JSON list of {prompt, wav, seed?, duration?, note?}")
    ap.add_argument("--output-dir", default="presentation/demo_clips")
    args = ap.parse_args()

    demos = json.loads(Path(args.demos).read_text(encoding="utf-8"))
    if not demos:
        print("no demos listed -- nothing to build, and no placeholder will be "
              "invented. The video ships without a demo section.")
        return 1

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    clips = []
    for i, demo in enumerate(demos, start=1):
        clip = build_scene(demo, i, len(demos), out_dir)
        clips.append(clip)
        print(f"  {clip.name}   {probe_duration(clip):5.1f}s   "
              f"{demo['prompt'][:56]}...")

    listing = out_dir / "demo_concat.txt"
    listing.write_text("".join(f"file '{c.resolve()}'\n" for c in clips))
    print(f"\n{len(clips)} demo scene(s) -> {out_dir}")
    print(f"concat list: {listing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
